export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const USER_SIGNOUT_REQUEST = "USER_SIGNOUT_REQUEST";
export const USER_SIGNOUT_SUCCESS = "USER_SIGNOUT_SUCCESS";
export const USER_SIGNOUT_FAILURE = "USER_SIGNOUT_FAILURE";

export const LOGGED_USER_INFO_REQUEST = "LOGGED_USER_INFO_REQUEST";
export const LOGGED_USER_INFO_SUCCESS = "LOGGED_USER_INFO_SUCCESS";
export const LOGGED_USER_INFO_FAILURE = "LOGGED_USER_INFO_FAILURE";